#2: restructured the repo
metno/S-ENDA-metadata pull request #3
Opened 2020-09-09 08:24 UTC by mortenwh

2020-09-09 18:46 UTC, lcoram requested changes

2020-09-09 18:46 UTC, lcoram commented on README.md
> +* Add an issue to the current repository (e.g., “New foo model dataset” [the issue is numbered, e.g., 131])
"add an issue to this repository"

2020-09-09 18:46 UTC, lcoram commented on README.md
> +* Clone the current repository
clone this repository OR clone the S-ENDA-metadata repository (otherwise I find it confusing since previously you cloned a different repository...)

2020-09-09 18:46 UTC, lcoram commented on in-situ/fixed-ground-station/README.md
> +MMD files for datasets from fixed ground stations
remove "ground" to be more generic (boats... etc.)

2020-09-10 06:19 UTC, ElodieFZ commented
What do you think could be stored in the 'misc' folder @mortenwh ? I think that if one starts producing MMD files that do not fit the existing structure, they should request the addition of a new "themed" repository rather that storing them in a miscellaneous folder.

2020-09-10 07:15 UTC, merged